apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: manifest-api
          image: europeana/manifest-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/info
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/info
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: secret
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/iiif.user.properties"
              readOnly: true
              subPath: iiif.user.properties
      volumes:
        - name: secret
          secret:
            secretName: iiif-api-secret