resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: iiif-api

# expects files to be in the same directory
secretGenerator:
  - name: iiif-api-secret
    files:
      - iiif.user.properties