apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiif-api-deployment
spec:
  template:
    spec:
      containers:
        - name: iiif-api
          # required to use local image
          imagePullPolicy: Never